name: Test
on: pull_request
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
